export interface Product {
  id: string
  slug: string
  brand: string
  name: string
  code: string
  category: string
  subcategory?: string
  oldPrice: number
  price: number
  priceUSD: number
  priceWithoutTax: number
  discount: number
  size: string
  coupon?: string
  images: string[]
  description: string
  features: string[]
  technicalSpecs: {
    label: string
    value: string
  }[]
  applications: string[]
  coverage: string
  dryingTime: string
  relatedProducts?: string[]
}

export const products: Product[] = [
  {
    id: "1",
    slug: "sherwin-williams-quantum-cielorrasos-mate-20l",
    brand: "SHERWIN WILLIAMS",
    name: "Quantum Látex para Cielorrasos Mate 20L",
    code: "QC-20-001",
    category: "Látex para Interiores",
    subcategory: "Cielorrasos",
    oldPrice: 89990,
    price: 62993,
    priceUSD: 62.99,
    priceWithoutTax: 52060,
    discount: 30,
    size: "20 lts",
    coupon: "Extra10",
    images: ["/images/quantum-cielorrasos-20l.png", "/images/pintura-hogar.jpeg", "/images/pintura-hogar2.jpeg"],
    description:
      "Látex acrílico premium especialmente formulado para cielorrasos. Quantum Cielorrasos ofrece extra blancura y bajo salpicado, con propiedades antihongos, antialgas y anticondensante. Su excelente poder cubritivo y terminación mate perfecta lo convierten en la elección ideal para renovar o pintar cielorrasos en interiores.",
    features: [
      "Extra blancura para máxima luminosidad",
      "Bajo salpicado para trabajo limpio",
      "Antihongos y antialgas",
      "Anticondensante para ambientes húmedos",
      "Excelente poder cubritivo",
      "Terminación mate perfecta",
      "Fácil aplicación",
      "Rápido secado",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Látex acrílico mate" },
      { label: "Contenido", value: "20 litros" },
      { label: "Color", value: "Blanco" },
      { label: "Acabado", value: "Mate" },
      { label: "Dilución", value: "Listo para usar o diluir 10% con agua" },
      { label: "Capas recomendadas", value: "2 capas" },
    ],
    applications: ["Cielorrasos interiores", "Ambientes secos y húmedos", "Hogares", "Oficinas", "Comercios"],
    coverage: "12-14 m² por litro por mano",
    dryingTime: "Al tacto: 30 min | Entre manos: 2 horas",
    relatedProducts: ["2", "5", "10"],
  },
  {
    id: "2",
    slug: "sherwin-williams-loxon-impermeabilizante-frentes",
    brand: "SHERWIN WILLIAMS",
    name: "Loxon Impermeabilizante Elástico para Frentes",
    code: "LX-IMP-001",
    category: "Impermeabilizantes",
    subcategory: "Exteriores",
    oldPrice: 124990,
    price: 87493,
    priceUSD: 87.49,
    priceWithoutTax: 72307,
    discount: 30,
    size: "20 lts",
    images: ["/images/loxon-impermeabilizante.png", "/images/piscinas-2.jpeg", "/images/pintura-industrial.jpeg"],
    description:
      "Revestimiento impermeabilizante elástico de tecnología avanzada. Loxon Impermeabilizante protege frentes y medianeras contra la humedad, con propiedades antihongos y antialgas. Su elasticidad permite adaptarse a los movimientos naturales de la construcción, garantizando colores más duraderos.",
    features: [
      "Impermeabilización garantizada",
      "Alta elasticidad y flexibilidad",
      "Antihongos y antialgas",
      "Colores más duraderos",
      "Resistente a la intemperie",
      "Tecnología Acme-Color",
      "Excelente adherencia",
      "Protección de larga duración",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Impermeabilizante elástico" },
      { label: "Contenido", value: "20 litros" },
      { label: "Base", value: "Acrílica" },
      { label: "Acabado", value: "Satinado" },
      { label: "Dilución", value: "Primera mano 10%, segunda mano sin diluir" },
      { label: "Capas recomendadas", value: "2-3 capas" },
    ],
    applications: ["Frentes", "Medianeras", "Muros exteriores", "Revoques", "Superficies de hormigón"],
    coverage: "8-10 m² por litro por mano",
    dryingTime: "Al tacto: 1 hora | Entre manos: 4 horas",
    relatedProducts: ["3", "9", "4"],
  },
  {
    id: "3",
    slug: "sherwin-williams-loxon-exterior-mate",
    brand: "SHERWIN WILLIAMS",
    name: "Loxon Exterior Mate 100% Acrílico",
    code: "LX-EXT-001",
    category: "Látex para Exteriores",
    oldPrice: 94990,
    price: 66493,
    priceUSD: 66.49,
    priceWithoutTax: 54956,
    discount: 30,
    size: "20 lts",
    images: ["/images/loxon-exterior-mate.png", "/images/pintar-casa-profesional.jpeg", "/images/pintura-home-03.jpeg"],
    description:
      "Látex 100% acrílico de máxima calidad para exteriores. Loxon Exterior Mate ofrece extra resistencia a las condiciones climáticas, excelente poder cubritivo y protección antihongos. Su fórmula avanzada garantiza una terminación mate perfecta y duradera en todos tus proyectos exteriores.",
    features: [
      "100% acrílico de primera calidad",
      "Extra resistente a la intemperie",
      "Excelente poder cubritivo",
      "Protección antihongos",
      "Terminación mate uniforme",
      "Alta durabilidad",
      "Resistente al lavado",
      "Colores estables al sol",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Látex 100% acrílico mate" },
      { label: "Contenido", value: "20 litros" },
      { label: "Acabado", value: "Mate" },
      { label: "Dilución", value: "Primera mano 10%, segunda sin diluir" },
      { label: "Capas recomendadas", value: "2 capas" },
    ],
    applications: ["Fachadas", "Muros exteriores", "Revoques", "Superficies de cemento", "Bloques de hormigón"],
    coverage: "10-12 m² por litro por mano",
    dryingTime: "Al tacto: 45 min | Entre manos: 3 horas",
    relatedProducts: ["2", "9", "1"],
  },
  {
    id: "4",
    slug: "sherwin-williams-quantum-membrana-fibrada-techos",
    brand: "SHERWIN WILLIAMS",
    name: "Quantum Membrana Fibrada para Techos y Terrazas 5Kg",
    code: "QM-TT-001",
    category: "Impermeabilizantes",
    subcategory: "Techos",
    oldPrice: 45990,
    price: 32193,
    priceUSD: 32.19,
    priceWithoutTax: 26612,
    discount: 30,
    size: "5 kg",
    images: ["/images/quantum-membrana-techos.png", "/images/piscinas-2.jpeg", "/images/pintura-industrial.jpeg"],
    description:
      "Membrana impermeabilizante fibrada de última generación para techos y terrazas transitables. Quantum Membrana sella goteras y filtraciones con su red poliuretánica integrada, ofreciendo mayor resistencia y durabilidad. Ideal para proteger techos planos, terrazas y azoteas.",
    features: [
      "Transitable - soporta tránsito peatonal",
      "Sella goteras y filtraciones",
      "Red poliuretánica integrada",
      "Mayor resistencia mecánica",
      "Elasticidad superior",
      "Resistente a rayos UV",
      "Aplicación en frío",
      "Secado rápido",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Membrana acrílica fibrada" },
      { label: "Contenido", value: "5 kilogramos" },
      { label: "Color", value: "Blanco/Terracota" },
      { label: "Transitabilidad", value: "Transitable" },
      { label: "Aplicación", value: "En frío con llana o rodillo" },
      { label: "Capas recomendadas", value: "2-3 capas" },
    ],
    applications: [
      "Techos planos transitables",
      "Terrazas",
      "Azoteas",
      "Balcones",
      "Losas de hormigón",
      "Reparación de filtraciones",
    ],
    coverage: "1-1.5 kg por m² en 2 manos",
    dryingTime: "Al tacto: 2 horas | Entre manos: 6 horas",
    relatedProducts: ["2", "9", "3"],
  },
  {
    id: "5",
    slug: "sherwin-williams-quantum-cielorrasos-mate-10l",
    brand: "SHERWIN WILLIAMS",
    name: "Quantum Látex para Cielorrasos Mate 10L",
    code: "QC-10-001",
    category: "Látex para Interiores",
    subcategory: "Cielorrasos",
    oldPrice: 44990,
    price: 31493,
    priceUSD: 31.49,
    priceWithoutTax: 26034,
    discount: 30,
    size: "10 lts",
    images: ["/images/quantum-cielorrasos-10l.png", "/images/pintura-hogar.jpeg", "/images/pintura-hogar2.jpeg"],
    description:
      "Látex acrílico premium para cielorrasos en presentación de 10 litros. Quantum Cielorrasos combina extra blancura con bajo salpicado, ideal para trabajos más pequeños o de retoque. Con propiedades antihongos, antialgas y anticondensante, garantiza un acabado profesional.",
    features: [
      "Extra blancura",
      "Bajo salpicado",
      "Antihongos y antialgas",
      "Anticondensante",
      "Excelente cubritivo",
      "Mate perfecto",
      "Tamaño ideal para ambientes medianos",
      "Fácil aplicación",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Látex acrílico mate" },
      { label: "Contenido", value: "10 litros" },
      { label: "Color", value: "Blanco" },
      { label: "Acabado", value: "Mate" },
      { label: "Dilución", value: "Listo para usar o diluir 10%" },
      { label: "Capas recomendadas", value: "2 capas" },
    ],
    applications: ["Cielorrasos", "Habitaciones", "Comedores", "Livings", "Dormitorios"],
    coverage: "12-14 m² por litro por mano",
    dryingTime: "Al tacto: 30 min | Entre manos: 2 horas",
    relatedProducts: ["1", "6", "10"],
  },
  {
    id: "6",
    slug: "sherwin-williams-loxon-cielorrasos-mate-20l",
    brand: "SHERWIN WILLIAMS",
    name: "Loxon Cielorrasos Mate 20L",
    code: "LX-CIE-001",
    category: "Látex para Interiores",
    subcategory: "Cielorrasos",
    oldPrice: 74990,
    price: 52493,
    priceUSD: 52.49,
    priceWithoutTax: 43390,
    discount: 30,
    size: "20 lts",
    images: ["/images/loxon-cielorrasos-20l.png", "/images/pintura-hogar.jpeg", "/images/pintura-hogar2.jpeg"],
    description:
      "Látex de larga duración especialmente formulado para cielorrasos. Loxon Cielorrasos ofrece excelente poder cubritivo con bajo salpicado, más blanco y protección antihongos y anticondensante. Su fórmula avanzada garantiza una terminación mate perfecta y duradera.",
    features: [
      "Larga duración",
      "Antihongos y anticondensante",
      "Excelente poder cubritivo",
      "Más blanco",
      "Bajo salpicado",
      "Tecnología Acme-Color",
      "Terminación mate",
      "Fácil aplicación",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Látex acrílico mate" },
      { label: "Contenido", value: "20 litros" },
      { label: "Color", value: "Blanco" },
      { label: "Acabado", value: "Mate" },
      { label: "Dilución", value: "10% con agua" },
      { label: "Capas recomendadas", value: "2 capas" },
    ],
    applications: ["Cielorrasos interiores", "Ambientes con humedad", "Baños", "Cocinas", "Lavanderías"],
    coverage: "12-14 m² por litro por mano",
    dryingTime: "Al tacto: 30 min | Entre manos: 2 horas",
    relatedProducts: ["1", "5", "7"],
  },
  {
    id: "7",
    slug: "sherwin-williams-loxon-cielorrasos-metal-20l",
    brand: "SHERWIN WILLIAMS",
    name: "Loxon Cielorrasos Mate 20L (Lata Metálica)",
    code: "LX-CIE-002",
    category: "Látex para Interiores",
    subcategory: "Cielorrasos",
    oldPrice: 74990,
    price: 52493,
    priceUSD: 52.49,
    priceWithoutTax: 43390,
    discount: 30,
    size: "20 lts",
    images: ["/images/loxon-cielorrasos-metal.png", "/images/pintura-hogar.jpeg", "/images/pintura-hogar2.jpeg"],
    description:
      "Látex Loxon Cielorrasos en presentación con envase metálico premium. Misma fórmula de alta calidad con propiedades antihongos y anticondensante, excelente cubritivo y bajo salpicado. El envase metálico garantiza mejor conservación del producto.",
    features: [
      "Envase metálico premium",
      "Antihongos y anticondensante",
      "Excelente poder cubritivo",
      "Más blanco",
      "Bajo salpicado",
      "Larga duración",
      "Mejor conservación",
      "Terminación profesional",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Látex acrílico mate" },
      { label: "Contenido", value: "20 litros" },
      { label: "Color", value: "Blanco" },
      { label: "Acabado", value: "Mate" },
      { label: "Envase", value: "Lata metálica" },
      { label: "Capas recomendadas", value: "2 capas" },
    ],
    applications: ["Cielorrasos", "Proyectos profesionales", "Obras grandes", "Contratistas"],
    coverage: "12-14 m² por litro por mano",
    dryingTime: "Al tacto: 30 min | Entre manos: 2 horas",
    relatedProducts: ["6", "8", "1"],
  },
  {
    id: "8",
    slug: "sherwin-williams-loxon-cielorrasos-lata-4l",
    brand: "SHERWIN WILLIAMS",
    name: "Loxon Cielorrasos Mate (Lata 4L)",
    code: "LX-CIE-003",
    category: "Látex para Interiores",
    subcategory: "Cielorrasos",
    oldPrice: 18990,
    price: 13293,
    priceUSD: 13.29,
    priceWithoutTax: 10987,
    discount: 30,
    size: "4 lts",
    images: ["/images/loxon-cielorrasos-lata.png", "/images/pintura-hogar.jpeg", "/images/pintura-hogar2.jpeg"],
    description:
      "Látex Loxon Cielorrasos en práctica presentación de 4 litros con lata metálica. Ideal para proyectos pequeños, retoques o reparaciones. Mantiene todas las propiedades de la línea Loxon: antihongos, anticondensante y excelente cubritivo.",
    features: [
      "Presentación práctica 4L",
      "Lata metálica",
      "Antihongos y anticondensante",
      "Excelente poder cubritivo",
      "Bajo salpicado",
      "Ideal para retoques",
      "Fácil almacenamiento",
      "Terminación mate",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Látex acrílico mate" },
      { label: "Contenido", value: "4 litros" },
      { label: "Color", value: "Blanco" },
      { label: "Acabado", value: "Mate" },
      { label: "Envase", value: "Lata metálica" },
      { label: "Capas recomendadas", value: "2 capas" },
    ],
    applications: ["Retoques", "Ambientes pequeños", "Reparaciones", "Proyectos menores"],
    coverage: "12-14 m² por litro por mano",
    dryingTime: "Al tacto: 30 min | Entre manos: 2 horas",
    relatedProducts: ["6", "7", "5"],
  },
  {
    id: "9",
    slug: "sherwin-williams-quantum-impermeabilizante-frentes-4l",
    brand: "SHERWIN WILLIAMS",
    name: "Quantum Impermeabilizante para Frentes con Red Poliuretánica 4L",
    code: "QI-FR-001",
    category: "Impermeabilizantes",
    subcategory: "Frentes",
    oldPrice: 39990,
    price: 27993,
    priceUSD: 27.99,
    priceWithoutTax: 23139,
    discount: 30,
    size: "4 lts",
    images: [
      "/images/quantum-impermeabilizante-frentes.png",
      "/images/piscinas-2.jpeg",
      "/images/pintura-industrial.jpeg",
    ],
    description:
      "Impermeabilizante de alta tecnología con red poliuretánica integrada. Quantum Impermeabilizante protege frentes contra humedad y filtraciones gracias a su elasticidad y flexibilidad. Sella microfisuras y resiste la intemperie con alto poder cubritivo.",
    features: [
      "Red poliuretánica integrada",
      "Elástico y flexible",
      "Sella microfisuras",
      "Resistente a la intemperie",
      "Alto poder cubritivo",
      "Protección duradera",
      "Fácil aplicación",
      "Excelente adherencia",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Impermeabilizante con red" },
      { label: "Contenido", value: "4 litros" },
      { label: "Color", value: "Blanco/Beige" },
      { label: "Tecnología", value: "Red poliuretánica" },
      { label: "Dilución", value: "Primera mano 10%" },
      { label: "Capas recomendadas", value: "2-3 capas" },
    ],
    applications: ["Frentes", "Muros con microfisuras", "Medianeras", "Revoques exteriores", "Superficies porosas"],
    coverage: "8-10 m² por litro por mano",
    dryingTime: "Al tacto: 1 hora | Entre manos: 4 horas",
    relatedProducts: ["2", "4", "3"],
  },
  {
    id: "10",
    slug: "sherwin-williams-loxon-interior-mate",
    brand: "SHERWIN WILLIAMS",
    name: "Loxon Interior Mate - Látex de Máximo Cubritivo",
    code: "LX-INT-001",
    category: "Látex para Interiores",
    oldPrice: 84990,
    price: 59493,
    priceUSD: 59.49,
    priceWithoutTax: 49167,
    discount: 30,
    size: "20 lts",
    images: ["/images/loxon-interior-mate.png", "/images/pintura-hogar.jpeg", "/images/pintura-home-03.jpeg"],
    description:
      "Látex premium de máximo poder cubritivo para interiores. Loxon Interior Mate ofrece excelente lavabilidad y terminación profesional con protección antihongos. Su fórmula de larga duración garantiza paredes perfectas y fáciles de mantener en cualquier ambiente interior.",
    features: [
      "Máximo poder cubritivo",
      "Excelente lavabilidad",
      "Terminación mate profesional",
      "Protección antihongos",
      "Larga duración",
      "Tecnología Acme-Color",
      "Fácil aplicación",
      "Colores intensos y duraderos",
    ],
    technicalSpecs: [
      { label: "Tipo", value: "Látex acrílico mate premium" },
      { label: "Contenido", value: "20 litros" },
      { label: "Acabado", value: "Mate" },
      { label: "Lavabilidad", value: "Alta" },
      { label: "Dilución", value: "10% con agua" },
      { label: "Capas recomendadas", value: "2 capas" },
    ],
    applications: [
      "Paredes interiores",
      "Livings y comedores",
      "Dormitorios",
      "Pasillos",
      "Oficinas",
      "Áreas de alto tránsito",
    ],
    coverage: "12-14 m² por litro por mano",
    dryingTime: "Al tacto: 30 min | Entre manos: 2 horas",
    relatedProducts: ["1", "3", "6"],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getRelatedProducts(productId: string, limit = 4): Product[] {
  const product = products.find((p) => p.id === productId)
  if (!product || !product.relatedProducts) return products.slice(0, limit)

  return product.relatedProducts.map((id) => products.find((p) => p.id === id)).filter(Boolean) as Product[]
}
